using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HS_Save_Editor
{
    public enum Maps
	{
		DUST_SHELF = 1,
		THRONE_ROOM = 2,
		THRONE_ROOM_Q = 4,
		CASTLE_RUINS = 5,
		NORTH_MUNDEMAN = 6,
		SOUTH_MUNDEMAN = 7,
		VERDANT_COAST = 8,
		OTHERWORLD = 9,
		CASTLE_GROUNDS = 10,
		SANCTUARY = 11,
		THE_TUNNELS = 12,
		GLITCH = 13,
		LUDDERSHORE = 14,
		THE_TUNDRA = 15,
		FROZEN_SHORE = 16,
		HALLOW_GROUND = 17,
		SOUTHERN_SWAMP = 18,
		DRAGONS_LAIR = 19,
		CORRUPTED_CASTLE = 20,
		CASTLE_MONILLUD = 21,
		THRONE_ROOM_A = 22,
		THE_UNDERWORLD = 23,
		OTHERWORLD_p = 24,
		MOLTEN_CAVERN = 26,
		THE_DUNGEONS = 27,
		ITEM_SHOP = 28,
		CONVERGENCE = 29,
		TRIAL_OF_REALITY = 30, // "THE FINAL MOMENT = ,
		THE_FALLEN_WORLD = 33,
		THE_ROAD_TO_HELL = 34,
		HAUNTED_MANSE = 35,
		THE_MOONWELL = 36,
		SMUGGLERS_ROAD = 40,
		SMUGGLERS_RUIN = 41,
		UNKNOWN = 80
    }


}
